// Partitioned i18n. The content scripts (injected into
// musixmatch/gemini/diffchecker/typeform) used to load the FULL
// i18n-strings.js (725KB, ~350 keys × 26 languages) to use barely ~80 of
// those keys (toast.*/banner.*/dc.*/sf.*/hud.*/label.*/slack.needConfig.* +
// dynamic popup.btn.*). Now manifest.json points them to
// i18n-strings-content.js (231KB, generated by tools/assemble-i18n.mjs), a
// subset with ONLY those prefixes; the full file stays only in
// popup/options/info/diff.html.
//
// CONTRACT test: grep each t("literal-key") in ALL the files the manifest
// injects as a content script, against the subset's real keys — fails if any
// content script uses a key the subset does not have (drift: someone adds a
// new toast but does not regenerate the subset, or uses a key outside the 8
// approved prefixes).
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const EXT = fileURLToPath(new URL("..", import.meta.url)).replace(/\/+$/, "");
const fails = []; const ok = (c, m) => { console.log((c ? "✓ " : "✗ ") + m); if (!c) fails.push(m); };

// Source of truth for "what is a content script": manifest.json itself, not a
// hardcoded list here (if the manifest changes, this test keeps covering what
// is really injected).
const manifest = JSON.parse(fs.readFileSync(path.join(EXT, "manifest.json"), "utf8"));
const INFRA = new Set(["mxm-shortcuts.js", "i18n-strings-content.js", "mxm-i18n.js", "studio-strings.js", "btn-colors.js"]);
const contentFiles = [...new Set(manifest.content_scripts.flatMap((g) => g.js).filter((f) => !INFRA.has(f)))];
ok(contentFiles.length >= 15, `content script files detected from the manifest: ${contentFiles.length}`);
ok(manifest.content_scripts.every((g) => g.js.includes("i18n-strings-content.js")),
  "ALL content_scripts groups load i18n-strings-content.js (not the full one)");
ok(!manifest.content_scripts.some((g) => g.js.includes("i18n-strings.js")),
  "NO content_scripts group loads the full i18n-strings.js");

// Extract t("literal") keys from each content script file.
const usedKeys = new Set();
const dynamicPrefixesFound = new Set();
for (const f of contentFiles) {
  const src = fs.readFileSync(path.join(EXT, f), "utf8");
  const re = /\bt\(\s*(["'])((?:\\.|(?!\1)[^\\])*)\1/g;
  let m;
  while ((m = re.exec(src))) {
    const k = m[2];
    if (k.endsWith(".")) dynamicPrefixesFound.add(k); // e.g. "popup.btn." + variable
    else usedKeys.add(k);
  }
}
ok(usedKeys.size >= 70, `literal keys used by content scripts: ${usedKeys.size}`);
ok(dynamicPrefixesFound.has("popup.btn."), "detected the dynamic popup.btn.<key> pattern (button tooltips)");

const subsetSrc = fs.readFileSync(path.join(EXT, "i18n-strings-content.js"), "utf8");
const subset = new Function("window", subsetSrc + "\nreturn window;")({}).MXM_STRINGS;
const LANGS = Object.keys(subset);
ok(LANGS.length === 26, `the subset carries all 26 languages (had ${LANGS.length})`);

// Every literal key used must exist in ALL the subset's languages.
let missing = [];
for (const k of usedKeys) {
  for (const lang of LANGS) {
    if (!(k in subset[lang])) missing.push(`${lang}: missing "${k}"`);
  }
}
ok(missing.length === 0, `all literal keys used are in the subset × 26 languages` + (missing.length ? ` (${missing.length} missing, e.g.: ${missing.slice(0, 3).join(" | ")})` : ""));

// The dynamic prefix too: at least one real popup.btn.* key in each language.
for (const lang of LANGS) {
  const hasAny = Object.keys(subset[lang]).some((k) => k.startsWith("popup.btn."));
  if (!hasAny) missing.push(`${lang}: no popup.btn.* at all`);
}
ok(missing.filter((m) => m.includes("popup.btn")).length === 0, "each language has at least one real popup.btn.* key");

// Sanity: the subset really is smaller than the full one (if it ever grows
// unintentionally, this catches it).
const fullSize = fs.statSync(path.join(EXT, "i18n-strings.js")).size;
const subsetSize = fs.statSync(path.join(EXT, "i18n-strings-content.js")).size;
ok(subsetSize < fullSize * 0.6, `the subset weighs noticeably less than the full one (${subsetSize} vs ${fullSize} bytes)`);

if (fails.length) fails.forEach((m) => console.log("  detail:", m));
console.log(fails.length ? `\n${fails.length} FAILURE(S)` : "\nOK");
process.exit(fails.length ? 1 : 0);
